version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:379734466033:task-definition/aws-currency-exchange:3"
        LoadBalancerInfo:
          ContainerName: "aws-currency-exchange-service-h2"
          ContainerPort: "8000"
        PlatformVersion: "LATEST"